definitions:
  http_errors.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.PathResponse:
    properties:
      path:
        items:
          $ref: '#/definitions/models.Point'
        type: array
      path_depth:
        type: integer
    type: object
  models.Point:
    properties:
      description:
        type: string
      id:
        type: string
      nums:
        items:
          type: string
        type: array
      photo:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
  models.PointResponse:
    properties:
      photo_base64:
        type: string
      point:
        $ref: '#/definitions/models.Point'
    type: object
info:
  contact: {}
  description: API Docs of UUST Navigator
  title: UUST Navigator
  version: "1.0"
paths:
  /path/navigate:
    get:
      consumes:
      - application/json
      description: Finds path by start point and end point
      parameters:
      - description: id of start point of path
        in: query
        name: start
        required: true
        type: string
      - description: id of end point of path
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PathResponse'
      summary: Find path
      tags:
      - path
  /points/:
    get:
      consumes:
      - application/json
      description: Finds points by query matches in tags, description and cabinets
        nearby
      parameters:
      - description: query for searching points
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Point'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_errors.HTTPError'
      summary: Find points by query
      tags:
      - points
  /points/{id}:
    get:
      consumes:
      - application/json
      description: Gets point by id from data and returns to user
      parameters:
      - description: Point ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PointResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_errors.HTTPError'
      summary: Get point by id
      tags:
      - points
swagger: "2.0"
